DROP USER admin;
DROP USER dataentry;
DROP USER turbo;
CREATE USER admin WITH PASSWORD 'adm1nPa55' CREATEROLE CREATEDB;
CREATE USER dataentry WITH PASSWORD 'dataPa55';
CREATE USER turbo WITH PASSWORD 'ta5tic!';
