DROP TABLE vms;
CREATE TABLE vms (
id SERIAL NOT NULL,
displayname VARCHAR(50) NOT NULL,
startcmd VARCHAR(255) NOT NULL,
stopcmd VARCHAR(255) NOT NULL,
statuscmd VARCHAR(255) NOT NULL
);
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE vms TO dataentry;
GRANT SELECT ON TABLE vms TO turbo;

DROP TABLE apps;
CREATE TABLE apps (
id SERIAL NOT NULL,
appname VARCHAR(50) NOT NULL,
environment VARCHAR(30) NOT NULL,
startorder VARCHAR(255) NOT NULL,
stoporder VARCHAR(255) NOT NULL
);
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE apps TO dataentry;
GRANT SELECT ON TABLE apps TO turbo;